### ISSUE TITLE
hsimp licence

### ISSUE THREAD

**Issue by publicarray** [technonerdz/passwordsecurity.info#2]
You need to add the licence from https://github.com/howsecureismypassword/hsimp
as stated in the MIT licence:

"The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software."

**Comment by technonerdz** [comment]
Good point!

**Comment by technonerdz** [comment]
Thanks for pointing this out

**Comment by publicarray** [comment]
No problem and congrats on winning the Lenovo!

**Comment by technonerdz** [comment]
Thank you!
